:PROPERTIES:
:ID:       43735876-8513-4992-9216-2245154a9d04
:END:
#+title: Scripting

programming language that is used to manipulate, customize, and automate the facilities of an existing system.

Scripting languages are usually [[id:bf416986-69aa-48e4-a84b-89aa06d16f2e][Interpreted]] at runtime rather than [[id:60d16def-55c3-4f88-98c4-b9b6382fad00][Compiled]].

- [[id:45bb23df-e29d-46dc-b704-f17cf26af1d7][Windows]] environments: batch scripts =(.bat)=, Powershell =(.ps1)=, Visual Basic Script =(.vbs)=
- [[id:a5441999-e7a7-4034-b996-cfc8462989ed][Linux/Unix]] environments: Shell scripts =(.sh)=
- Most [[id:1dcff204-74cf-445d-9357-5c01ca3d2a03][OS]] environments: javascript =(.js)=, Python =(.py)=

*** Scripting:
** Basic automation
Python is an excellent script for automation.
It’s one of the most commonly used, with many available automation libraries.

** Restarting machines
Many power users use PowerShell (.ps1) scripts to restart machines (Windows). For Linux machines, they can use .sh (shell) scripts.

** Mapping network drives
In the past, mapping network drives was accomplished with =.bat= or =.vbs= scripts.

However, =PowerShell= scripts are most commonly used to map drives in =Windows= environments today.

For Linux users, =shell scripts= can be used for this purpose.

** Installing applications
=Batch file= and =shell scripts= are often used for automated software installation.

** Automated Backups
Windows =PowerShell= and Linux/Unix =shell scripts= can automate backups.

** Gathering of information and data
Python is a popular choice for gathering data.

Python has many available libraries to help with this task.

** Initiating Updates
=Powershell= and =shell= scripts can be used for initiating updates in Windows and Linux, respectively.
