:PROPERTIES:
:ID:       939fb878-342f-4e26-963d-2e35c1efd5a0
:END:
#+title: Projectors

* Device Drivers
If your computer does not correctly recognize the display resolution of the projector it may default to a very low-resolution =VGA= mode like *640x480* or *1024x768*.

If this happens, your computer may need a device driver for your projector.

* Lighting
Projectors often rely on expensive, hot, very bright *incandescent* bulbs.

If a projector gets too hot for the lamp to safely operate, the projector will shut down.

If the lamp burns out, the projector will either not work or will shut itself down.

It is increasingly common for projectors to rely on *LED* lights, rather than *incandescent* bulbs.

LED lights have fewer issues with overheating, and have much longer lifespans.

* Calibration

Sometimes, like when a projector is first installed, reset, or moved, you will need to calibrate the projector image to account for the distance and angle that the projector is installed at.

If the image is skewed you might need to recalibrate the projector geometry (See: [[id:99bf9995-82e0-4a67-bea0-e2ffbe0aec1f][Keystone]])

Calibrating the image involves focusing the image, and making adjustments to the image to make it square and aligned with the projection surface.
