:PROPERTIES:
:ID:       6cdb132b-74df-4a3f-873b-c5e5bb62c373
:END:
#+title: Communication Connectors

* Plain Old Telephone Service (POTS)
Cables transmitting voice through twisted copper pair wires.

Landline telephones, dial-up internet, and alarm systems use ~POTS~.

The =RJ-11= (Register Jack 11) connector is used for ~POTS~.

* Digital Subscriber Line (DSL)
Provides access to high-speed networks or the internet through telephone lines and a modem.
The =RJ-45= connects a computer to network elements and is mostly used with ethernet cables.

* Cable Internet
Uses a cable TV infrastructure and a modem to provide high-speed internet access to users.
An =F-type= connector is commonly used with cable modems.

* Fiber-optic cables
Contain strands of glass fibers inside an insulated casing that send data long-distance and allow for higher-bandwidth communication.

The major internet providers use *fiber-optic cables* for high-speed internet service.

[[id:1790e84d-6eb8-4f9b-8abf-1b9a9f833bd6][Wireless Networking Technologies]]
