:PROPERTIES:
:ID:       37b247e7-d20d-4e35-a0e7-05acd9261748
:END:
#+title: Cryptanalysis Attack Damages

* Instance deduction
Attacker discovers *additional* =plain/cipher text=.
While the key isn’t found to break the code, the additional =plain/ciphertext= can be used to cause problems/continue attacks.

* Information deduction
Attacker obtains some information about =plain/ciphertext= not previously known.
The additional information can lead to more information about the encryption key.

* Distinguishing algorithm
where the attacker can *distinguish* the [[id:d5db0593-2283-4d73-b904-bcd9f32717ce][algorithm]] from a random alteration.
This information reveals clues about the [[id:d5db0593-2283-4d73-b904-bcd9f32717ce][algorithm]] and can lead to more significant breaks.

* Global deduction
Attacker finds an [[id:d5db0593-2283-4d73-b904-bcd9f32717ce][algorithm]] that is functionally equivalent to the one used in the *key*.
This algorithm is then used to [[id:e35c79e8-db3e-4c13-9ad3-1a8f4387fa60][decrypt]] all information and messages.

* Total break
Attacker can gain the entire *key*.
With the entire key, the attacker can [[id:e35c79e8-db3e-4c13-9ad3-1a8f4387fa60][decrypt]] all messages and information.
