:PROPERTIES:
:ID:       434b40ba-6fee-45ee-95e0-f8b79f751cdd
:ROAM_ALIASES: CPU
:END:
#+title: Central Processing Unit (CPU)

Computer's Brain.
Retrieves intruction from the Memory [[id:73ee7657-201d-4041-acfd-c05bdfaeb118][(RAM)]].

Our =CPU= has an internal clock that keeps its operations in *sync*.

It connects to a special wire called a =clock wire=.

When you *send* or *receive* *data*, it sends a *voltage* to that =clock wire= to let the *CPU* know it can start doing calculations.

Think of our clock wires as the ticking of a clock, for every tick the CPU does one cycle of operations.

When you send a *voltage* to the clock wire it's referred to as a *clock cycle*.


The CPU usually has *two* components:
- [[id:22ee54dc-1839-4960-883f-a19785e67a8c][Control Unit]]
- [[id:faedeb6e-289a-4fe3-892d-c728f5ac0a42][Arithmetic/logic Unit]]


Today’s *CPUs* are built on small silicon ~semiconductor~ chips that contain millions of tiny electric switches, called ~transistors~, for processing information.

Every computer has an *internal* *clock* that emits electronic pulses at a constant rate.

These pulses are used to *control* and *synchronize* the pace of operations.
A *higher* clock speed enables *more* *instructions* to be executed in a given period of time.

The unit of measurement of clock speed is the *hertz* (*Hz*), with *1* *Hz* equaling *1* *pulse* *per* *second*.

In the ~1990s~, computers measured clock speed in *megahertz* (*MHz*, i.e., *1* *million* *pulses* *per* *second*), but CPU speed has been *improving* continuously.

The clock speed of a computer is now usually stated in *gigahertz* (*GHz*, i.e., *1* *billion* *pulses* *per* *second*).

Intel’s newest processors run at about 3 GHz.

CPUs were originally developed with only *one* core.

The ~core~ is the part of the processor that performs the *reading* and *executing* of instructions.

In order to increase the CPU processing power, chip manufacturers are now producing CPUs that contain *multiple* cores.

A multicore CPU is a single component with *two* or *more* independent cores.
Today’s consumer computers typically have *two*, *four*, and even *eight* separate cores.

See: [[id:15f9f642-ca9e-4930-870b-bcf13ee334d5][Overclocking]]

[[id:c7e3663c-4169-4a6b-b78c-aa2bc5e7dbf3][CPU Sockets]]
