:PROPERTIES:
:ID:       5527481e-3a34-41fc-b798-d1509a9b887a
:END:
#+title: Quotes

"It's hardware that makes a machine fast. It's software that makes a fast machine slow." - Craig Bruce

"Write code that is easy to delete, not easy to extend." - Tef, Programming is Terrible

"Computers are actually easy machines to secure: just turn them off, lock them in a metal-lined room, and throw away the key." - Peter G. Neumann

"Making it so simple that there are obviously no deficiencies." - Tony Hoare

"The only constant in the technology industry is change." - Marc Benioff

"Do One Thing and Do It Well" - UNIX Philosophy

"Whatever you do will be insignificant, but it is very important that you do it." - Mahatma Gandhi

"If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is." — [[id:eb84dd5c-fc6b-4c60-92cf-ca0bce1f215a][John von Neumann]]

"For me, great algorithms are the poetry of computation. Just like verse, they can be terse, allusive, dense, and even mysterious. But once unlocked, they cast a brilliant new light on some aspect of computing. ” — Francis Sullivan

“ An algorithm must be seen to be believed. ” — Donald Knuth

“ I will, in fact, claim that the difference between a bad programmer and a good one is whether he considers his code or his data structures more important. Bad programmers worry about the code. Good programmers worry about data structures and their relationships. ” — [[id:4d6f88bb-2555-48b3-a949-062d4e38b8a9][Linus Torvalds]]

"May your loops terminate and your exceptions get caught!" - Unkown

"C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do it blows your whole leg off." - Bjarne Stroustrup

"Precise language is not the problem. Clear language is the problem." - Richard Feynman

"Don’t imagine you know what a computer terminal is. A computer terminal is not some clunky old television with a typewriter in front of it.
It is an interface where the mind and the body can connect with the universe and move bits of it about.""
- DOUGLAS ADAMS, Mostly Harmless (the fifth volume in The Hitchhiker’s Trilogy)

"Once a person has understood the way variables are used in programming, he has understood the quintessence of programming." - E. W. DIJKSTRA, Notes on Structured Programming

"They’ll never be happy together. He’s not her type." - Overheard at a Cocktail Party
