:PROPERTIES:
:ID:       73ee7657-201d-4041-acfd-c05bdfaeb118
:ROAM_ALIASES: RAM
:END:
#+title: Random Access Memory (RAM)

* [[id:049093ad-96f5-491e-a3d9-b80f757109ab][Bits and Bytes]]

A computer’s ~memory~ consists of an ordered sequence of [[id:14267f9e-5fe8-441f-8e3a-3c77d5868bd0][Bytes]] for storing *programs* as well as *data* with which the program is working.

You can think of ~memory~ as the computer’s work area for executing a program.

A *program* and its *data* must be moved into the computer’s ~memory~ before they can be executed by the [[id:434b40ba-6fee-45ee-95e0-f8b79f751cdd][CPU]].

Every byte in the memory has a unique ~address~.

The ~address~ is used to locate the [[id:14267f9e-5fe8-441f-8e3a-3c77d5868bd0][byte]] for *storing* and *retrieving* the data.

Since the [[id:14267f9e-5fe8-441f-8e3a-3c77d5868bd0][bytes]] in the memory can be accessed in any order, the memory is also referred to as ~random-access memory (RAM)~.

A memory [[id:14267f9e-5fe8-441f-8e3a-3c77d5868bd0][byte]] is never *empty*, but its initial content may be meaningless to your program.

The current content of a memory byte is lost whenever new information is placed in it.

Like the [[id:434b40ba-6fee-45ee-95e0-f8b79f751cdd][CPU]], memory is built on ~silicon semiconductor chips~ that have millions of *transistors* embedded on their surface.

Compared to CPU chips, memory chips are less complicated, slower, and less expensive.

* Types

** Dynamic Random Access Memory (DRAM).

When 1 or 0 is sent to DRAM, it stores each bit in a microscopic capacitor, this is either *charged (1)* or *discharged (0)*.

These semiconductors are put into chips that are on the RAM and store our data.

There are also different types of memory sticks that =DRAM= chips can be put on.

The more modern DIMM sticks which usually stands for Dual Inline Memory Module have different sizes of pins on them.

**  Synchronous Dynamic Random Access Memory (SDRAM).
After DRAM was created, RAM manufacturers built something =SDRAM=.

This type of RAM is *synchronized* to our system's *clock speed*, allowing quicker processing of data.

** Double Data Rate SDRAM (DDR)
=DDR= is *faster*, takes up *less power*, and has a larger capacity than earlier =SDRAM= versions.

In today's system, we use another type of RAM called =DDR=.

Types:
- DDR1
- DDR2
- DDR3
- DDR4
