:PROPERTIES:
:ID:       b0c23be4-f4a8-431b-9c4b-81ccb00a40ab
:ROAM_ALIASES: DDoS
:END:
#+title: Distributed Denial-of-Service Attack (DDoS)

[[id:075ef02e-9d9b-418d-be84-9ca16a1bd79f][DoS Attack]] using *multiple* systems.

And they're usually helped by [[id:ca248324-6746-4bdd-994c-42f69cb33f8d][botnet]] attackers.

* Examples in history:
** 2020 AWS
The AWS Shield Threat Landscape Report for Q1 of 2020 described the largest DDoS attack to date.

AWS cloud servers were inundated by incoming traffic at a rate of 2.3 Tbps over a three day period.

The peak of the attack was 44% larger than anything the AWS Shield service has experienced previously.

The DDoS attack target was an undisclosed AWS cloud platform customer.

Attackers took over [[id:7539b2da-ff52-4ee9-944d-940d75b61462][CLDAP]] web servers.
In recent years, numerous DDoS assaults have utilized [[id:7539b2da-ff52-4ee9-944d-940d75b61462][CLDAP]].

** 2018 Github
This attack sent 126.9 million packets per second, reaching a throughput of 1.3 Tbps.

This DDoS attack used =memcaching=, which takes advantage of a database caching system for an amplified attack impact.

The attackers were able to magnify their attack by a factor of around 50,000x by saturating memcached servers with bogus queries.

Github’s DDoS security provider successfully alerted the company within 10 minutes of the onset, allowing Github to quickly stop the assault and work to restore operations.

** 2017 Google Cloud
This DDoS attack against Google Cloud services generated a magnitude of 2.54 Tbps.

Approximately *180,000* web servers were targeted by the attackers, who used fake packets to send responses to Google.

The attack was not an isolated occurrence.

During the previous six months, the perpetrators had launched many DDoS attacks against Google's infrastructure.

** 2016 Dyn DNS Service
Numerous notable websites, including Netflix, The New York Times, PayPal, Amazon, Airbnb, Reddit, Visa, and GitHub experienced downtime as a result of this destructive attack from malware known as [[id:a0c23a8c-6187-443d-aa7b-67338cf09d0e][Mirai]].

The malware configured the infected [[id:4e44f12e-f1aa-486a-a596-573347cc172d][IoT]] devices to make queries to Dyn in order to generate the attack traffic.

Thankfully, Dyn was able to stop the attack in one day, but the attack's purpose was never identified.


** 2015 Github
This DDoS attack was politically motivated and persisted for several days.

The attack adapted itself to circumvent Github’s DDoS mitigation measures.

The DDoS activity came from *China* and was directed at two GitHub projects that were trying to avoid Chinese government censorship.

It is believed that the goal of the attack was to exert pressure on GitHub to terminate such projects.

Cybercriminals used [[id:8cca6fb2-60e7-40bd-983b-4df5bac6ae01][Baidu]], to generate attack traffic by injecting *JavaScript* code into users' browsers.

Websites that used [[id:8cca6fb2-60e7-40bd-983b-4df5bac6ae01][Baidu's]]  web traffic analytics services were used to inject malicious code in place of harmless visitor tracking scripts.

The code then prompted the affected browsers to make repeated [[id:d9ee14c8-ce84-46a5-9c63-4b1903d9866b][HTTP]] requests to the targeted GitHub pages.


** 2013 Spamhaus
An organization that aids in the fight against spam emails and spam-related behavior, fell victim in 2013 to what was then the largest DDoS attack to-date.

People who make money from spam emails commissioned the offense on the spam filtering service.

Spamhaus experienced *300 Gbps* of incoming internet traffic during the attack.

When the assault started, Spamhaus registered for Cloudflare, whose DDoS defense successfully reduced the volume of the bogus incoming traffic.

In an effort to take down Cloudflare, the attackers retaliated by targeting specific Internet exchanges and bandwidth suppliers.

Although this assault's objective was not met, it did serious harm to [[id:bba5be7f-57f3-4eb0-8c70-1b550aba3ee9][LINX]]

The primary attacker hired to organize this offense turned out to be a British teenager.
