:PROPERTIES:
:ID:       952f8ae2-e4fa-4464-89ed-08585895bde5
:ROAM_ALIASES: CM1030-01
:END:
#+title: How Computers Work [CM1030-01]

(Coursera Module)

* What is IT?
IT is essentially the use of digital technology like computers on the Internet to store and process data into useful information.
The IT industry refers to the entire scope of all the jobs and resources that are related to computing technologies within society.
And there are a lot of different types of jobs in this field.

[[id:7be5f9e0-d58c-4d3f-9fff-8706c9f8f8cc][Digital Divide]]

[[id:60cfcb90-c159-4770-b7d6-4ef5756c1816][Pioneers in Computing]]

[[id:c8f65fea-d52f-4b67-99b6-2faa09557397][Logic Gates]]

* Computer Architecture
** 1. Hardware Layer

Made up of the physical components of a computer.

** 2. Operating System Layer

The operating system allows hardware to communicate with the system.

Hardware is created by many different manufacturers.
The operating system allows them to be used with our system regardless of where it came from.

** 3. Software Layer

How we as humans interact with our computers.

When you use a computer, you're given a vast amount of software that you interact with.

Whether it's a mobile app, a web browser, a word processor with an OS itself.

** 4. User Layer

The most important part of IT is the human element.
While we work with computers every day, it is the user interaction that makes up most of our job from responding to user emails to fixing their computers.

* [[id:e84553c8-b876-4190-a670-bd533b55a774][The Modern Computer]]
* [[id:1dcff204-74cf-445d-9357-5c01ca3d2a03][Operating Systems]]
* [[id:81cf9704-e90a-4565-9337-3304436a50c2][Networking]]
