:PROPERTIES:
:ID:       34f737cd-7010-42aa-9f37-5136eb75a44e
:END:
#+title: 1. Building blocks
#+filetags: :OCP:
#+property: header-args :tangle code/ocp/1/summary.java

* Chapter 1. Building Blocks
** Exam Objectives
*** Handling date, time, text, numeric and boolean values
- Use primitives and ~wrapper~ classes including ~Math~ API, parentheses, *type promotion*, and *casting* to evaluate *arithmetic* and *boolean* expressions

*** Utilizing Java Object­Oriented Approach
- Declare and instantiate Java objects including ~nested class~ objects, and explain the object life­cycle including ~creation~, ~reassigning references~, and ~garbage collection~
- Understand *variable scopes*, use local variable type inference, apply [[id:89e69431-4199-42ee-8633-4c2cc5da4d8a][encapsulation]], and make objects *immutable*

| Name              | Description                                                                                                                                                                         |
|-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Instance Members  | The instance variables and instance methods of an object. members They can be accessed or invoked only through an object reference.                                                 |
| Instance Variable | A field that is allocated when the class is instantiated (i.e.,when an object of the class is created). Also called a non-static field or just a field when the context is obvious. |
| Instance method   | A method that belongs to an instance of the class. Objects of the same class share its implementation.                                                                              |
| Static Members    | The static variables and static methods of a class. They can be accessed or invoked either by using the class name or through an object reference.                                  |
| Static Variable   | A field that is allocated when the class is loaded. It belongs to the class, and not to any specific object of the class. Also called a static field or a class variable.           |
| Static Method     | A method that belongs to the class, and not to any object of the class. Also called a class method.                                                                                 |
|                   |                                                                                                                                                                                     |

** Compiling

(See also: [[id:17935397-ee6a-41e5-b492-4e3cc99c4c4a][Single File Source Code]])
Compiled using the [[id:d5b4004d-b5db-48a2-8e85-09359ca61a42][javac]]

- Each ~class~ declaration in a source file is compiled into a separate ~class file~, containing its Java bytecode.
- The name of this file comprises the name of the class with ~.class~ as its extension.
- Although a Java source file can contain more than one class declaration, [[id:d5b4004d-b5db-48a2-8e85-09359ca61a42][javac]] enforces the rule that there can *only be at the most* one class in the source file that has ~public access~ ([[id:f7f87f85-1d9b-468a-8947-cd839883c9fa][Top-Level Type]]).
- If there is a ~public class~ in the source file, the name of the source file must be the name of the public class with ~.java~ as its extension.
- In the *absence* of a public class in the source file, the name of the file can be arbitrary, but still with the ~.java~ extension.

** Running
It is the ~bytecode~ in the class files that is executed when a Java program is run—the source code is irrelevant in this regard.
A Java program is run by the Java Application Launcher, ~java~, which is also part of the *JDK*.
The ~java~ command creates an instance of the *JVM* that executes the bytecode.

** Packages
Java ~classes~ are grouped into *packages*

*** WildCards

A shortcut to import *all* the classes in a package is using a wildcard (~*~)
#+BEGIN_SRC java
// WildCards
import java.util.*; // imports java.util.Random among other things
public class NumberPicker {
    public static void main(String[] args) {
        Random r = new Random();
        System.out.println(r.nextInt(10));
    }
}
#+END_SRC

Every class in the ~java.util~ package is available to this program when Java compiles it.

The import statement does *not* bring in ~child packages, fields, or methods~.
It imports only ~classes~ *directly under the package*.

*** Redundant imports
Already imported automatically: ~import java.lang.*~

*** Invalid imports
Which import statements do you think would not work to get this code to compile?

#+BEGIN_SRC java
public class InputImports {
    public void read(Files files) {
        Paths.get("name");
    }
}
#+END_SRC

#+BEGIN_SRC java
// Invalid Imports
import java.nio.*;// NO GOOD -­a wildcard only matches // class names, not "file.Files"
import java.nio.*.*;// NO GOOD -­you can only have one wildcard // and it must be at the end
import java.nio.file.Paths.*; // NO GOOD -­you cannot import methods // only class names
#+END_SRC


#+BEGIN_SRC java
// Valid Imports
import java.nio.file.*;
// OR
import java.nio.file.Files;
import java.nio.file.Paths;
#+END_SRC

*** Naming Conflicts

Example: Java provides 2 implementations of the Date class: ~java.util.Date~ and ~java.sql.Date~

#+BEGIN_SRC java
// Collision
import java.util.*;
import java.sql.*; // causes Date declaration to not compile
#+END_SRC

#+BEGIN_SRC java
// Correct imports
import java.util.Date;
import java.sql.*;
#+END_SRC

#+BEGIN_SRC java
// Using Fully-Qualified Domain Names
public class Conflicts {
    java.util.Date date;
    java.sql.Date sqlDate;
}
#+END_SRC

*** [[id:c13f080f-e542-44d0-8311-5e4cdb388991][Creating a new package]]
*** [[id:e40da6d4-9a59-46c8-9a2f-c375c0d7dda8][Creating a JAR file]]
** [[id:73a0f36b-e440-486a-bd88-6ca577be3351][Constructors]]
** [[id:f041c4e7-7bfa-4554-9b25-6e6b8e086aec][Order of Initialization]]
