:PROPERTIES:
:ID:       9bc1f8df-b92d-4146-9a4a-65a02eedee6b
:END:
#+title: Assembly Language

Allows computer scientists to use human readable instructions assembled into code that the machines could understand.

Instead of generating binary code, computer scientists could program using machine instructions.

Programming in [[id:89afff2d-63e0-4cc8-87fb-b30d65018241][Machine Language]] is a tedious process (programs written in machine language are very difficult to read and modify).

~Assembly language~ was created in the early days of computing as an alternative to [[id:89afff2d-63e0-4cc8-87fb-b30d65018241][Machine Languages]].

Assembly language uses a short descriptive word, known as a [[id:90efaf04-9070-4ced-89ca-8ea66d0e0f1d][mnemonic]], to represent each of the [[id:89afff2d-63e0-4cc8-87fb-b30d65018241][Machine Language]] instructions.

For example, the [[id:90efaf04-9070-4ced-89ca-8ea66d0e0f1d][mnemonic]] *add* typically means to *add* numbers, and *sub* means to *subtract* numbers.

To *add* the numbers =2= and =3= and get the result, you might write an instruction in assembly code as follows:
~add 2, 3, result~

Because the computer cannot execute ~assembly language~, another program called an [[id:569c613f-04ec-4779-af82-8fffa5f6f5be][Assembler]]—is used to *translate* ~assembly-language~ programs into ~machine code~.

An instruction in ~assembly language~ corresponds to an instruction in ~machine code~.

Writing in assembly language requires that you know how the [[id:434b40ba-6fee-45ee-95e0-f8b79f751cdd][CPU]] works.

Assembly language is a [[id:b6446056-6b86-4e7e-8d68-1caa905473f5][low-level language]], because ~assembly language~ is *close* in nature to ~machine language~ and is machine *dependent*.

#+BEGIN_SRC asm
section	.text
   global _start     ;must be declared for linker (ld)

_start:	            ;tells linker entry point
   mov	edx,len     ;message length
   mov	ecx,msg     ;message to write
   mov	ebx,1       ;file descriptor (stdout)
   mov	eax,4       ;system call number (sys_write)
   int	0x80        ;call kernel

   mov	eax,1       ;system call number (sys_exit)
   int	0x80        ;call kernel

section	.data
msg db 'Hello, world!', 0xa  ;string to be printed
len equ $ - msg     ;length of the string
#+END_SRC
