:PROPERTIES:
:ID:       f2498bfe-5984-4990-8282-5f7e748a4303
:END:
#+title: Admiral Grace Hopper

9 December 1906 - 1 January 1992

During the Second World War, she joined the US Navy Reserve after taking a leave from her role as a mathematics professor at Vassar College.

In the Navy, she was assigned the Bureau of Ships Computation Project at Harvard University where she worked on the programming team for the [[id:a4dfea9e-8480-4ff7-a01e-c78fba7da0c4][Mark I Computer]].

After the war and her time at Harvard, she began working on more powerful computers and recommended that a programming language be developed that used English words rather than symbols.

This concept would eventually become FLOW-MATIC the first programming language to use English words which also necessitated the invention of the first [[id:44534722-acbc-4a80-8c65-3f76edefd7b5][Compiler]].

She is also credited with first using the term “computer bug” after a real bug (a moth) flew into a computer she was working on.

Later in her career, she was one of the designers of [[id:f5621d16-9902-47ee-b992-e1381bb0c09c][COBOL]], a programming language that is still in use today.
