:PROPERTIES:
:ID:       217735d8-7ee5-4ffc-9ac3-96db9bd2bf8e
:ROAM_ALIASES: PPPoE
:END:
#+title: Point-to Point Protocol Over Ethernet (PPPoE)

Way of encapsulating [[id:af28e275-e8b6-4bc5-a9b3-ca8dd6b72d46][PPP Frames]] inside an [[id:73b06fc5-e631-40ad-828f-741dd84bd15c][Ethernet Frame]].

=PPPoE= is a solution for tunneling packets over the DSL connection service provider's IP network and from there to the rest of the Internet.

PPPoE provides:
- Authentication
- Encryption
- Compression, though it primarily uses [[id:a8d5b07d-23ae-4384-8a67-75a14e05bd65][PAP]] for authentication.

PPPoE requires a new step because ethernet connections are multi-access enabled (every node connects to another):

This requires an additional step called the discovery stage.

The discovery stage establishes a session ID to identify the hardware address.
This stage ensures data gets routed to the correct place.

=PPPoE= is an encapsulation of [[id:fe39eea8-7c49-4942-9d84-a416722095ff][PPP]] inside an [[id:73b06fc5-e631-40ad-828f-741dd84bd15c][Ethernet Frame]].

PPPoE retains the same architecture, configuration options, and frame data as PPP but with one extra layer of ethernet encapsulation.
