:PROPERTIES:
:ID:       1790e84d-6eb8-4f9b-8abf-1b9a9f833bd6
:END:
#+title: Wireless Networking Technologies

Defined by =IEEE 802.11= standards.

Most commonly the 2.4Ghz and 5Ghz [[id:35766a1b-6bed-482a-b984-2493601f67da][Frequency Band]]s.

* Specifications:
- 802.11b
- 802.11a
- 802.11g
- 802.11n
- 802.11ac

802.11 : how we operate on both [[id:4a16abe5-9d6e-41e7-ac14-457479594c80][1. Physical Layer]] and [[id:a6d3f0e4-6871-401d-acea-0a58e4b6891a][2. Data Link Layer]]s

* 802.11 Frame
** Frame Control Field
*16 bits*
Contains a number of sub-fields that are used to describe how the frame itself should be processed. This includes things like what version of the 802.11 was used.

** Duration Field
Specifies how long the total frame is.

** 4 Address Fields (Each 6 Bytes long)
*** Source Address Field (MAC)
*** Intended Destination
*** [[id:d2687c6f-4af2-41eb-8395-dc95295f9dcd][Receiver Address]]
*** [[id:c0c78426-8f4b-4feb-9bfc-4d9dfb6c871e][Transmitter Address]]

** Sequence Control Field
*16 bits*
(In between =Receiver= and =Transmitter= Address Fields)

Contains a sequence number used to keep track of the ordering of frames after

** Data Payload
Has all of the data of the protocols further up the stack.

** Frame Check Sequence
Contains a checksum used for a cyclical redundancy check (just like how Ethernet does it)

* [[id:46cb7c35-247b-417d-ba51-4a02e222e2cc][Wireless Channels]]
* [[id:4cf68bc9-1c91-41c0-9264-b85b5ea42c45][Wireless Security]]
