:PROPERTIES:
:ID:       73ee7657-201d-4041-acfd-c05bdfaeb118
:ROAM_ALIASES: RAM
:END:
#+title: Random Access Memory (RAM)

Types:

* Dynamic Random Access Memory (DRAM).

When 1 or 0 is sent to DRAM, it stores each bit in a microscopic capacitor, this is either *charged (1)* or *discharged (0)*.

These semiconductors are put into chips that are on the RAM and store our data.

There are also different types of memory sticks that =DRAM= chips can be put on.

The more modern DIMM sticks which usually stands for Dual Inline Memory Module have different sizes of pins on them.

*  Synchronous Dynamic Random Access Memory (SDRAM).
After DRAM was created, RAM manufacturers built something =SDRAM=.

This type of RAM is *synchronized* to our system's *clock speed*, allowing quicker processing of data.

* Double Data Rate SDRAM (DDR)
=DDR= is *faster*, takes up *less power*, and has a larger capacity than earlier =SDRAM= versions.

In today's system, we use another type of RAM called =DDR=.

Types:
- DDR1
- DDR2
- DDR3
- DDR4
