:PROPERTIES:
:ID:       7a9a7651-d42f-4cd9-a140-c04c3704e2db
:END:
#+title: Hard Drives

[[id:3f94f217-3c98-4a7f-bb58-cc50fd7bd06c][Partition Table]]
[[id:6e7049bf-317d-447a-b039-84665602f05c][Data Corruption]]

There are two basic hard drive types used today.

* HDD
Uses a spinning platter and a mechanical arm to read and write information.

The speed that the platter rotate allows you to read and write data faster (RPM).

HDDs are prone to a lot more damage because there are a lot of moving parts.

This susceptibility to damage went away with a new type of storage called solid state drive or SSD.

* SSD

SSDs have no moving parts.

The information is stored on microchips and data travels a lot faster than HDDs.

There are a few interfaces that hard drives use to connect our system.

** Connecting Hard Drives
*** SATA
(Uses one cable for data transfers).
=SATA= drives are *hot swappable* (Don't have to turn off your machine to plug in a =SATA= drive).

*** NVMe
=SATA= interface couldn't keep up with the speeds of the newest SSDs So another interface standard was created called =NVM express= or =NVMe=.

