:PROPERTIES:
:ID:       0b5a5fb4-d919-44d5-a65b-953a84b23ced
:END:
#+title: Networking Cables

* Copper

The most common forms of copper twisted pair cables used in networking are =Cat5=, =Cat5e= and =Cat6= cables.

These categories have different physical characteristics like the number of twists in the pair of copper wires that result in different usable lengths and transfer rates.

=Cat5= is older and has been mostly replaced by =Cat5e= and =Cat6= cables.

The important thing to know is that, differences in how the twisted pairs are arranged inside these cables can drastically alter how quickly data can be sent across them. And how resistant these signals are to outside interference.

=Cat5e= cables have mostly replaced those older =Cat5= cables because their internals reduce [[id:b0383f97-1aa8-4779-8534-0fb0bf6c6a24][crosstalk]].

Higher level protocols have methods for detecting missing data and asking for the data a second time.

[[id:d9bc6d31-fa5b-498b-9281-ca5a936c7c02][Modulation]]

* Fibre

Fiber cables use pulses of light to represent the ones and zeros of the underlying data.

Fiber is even sometimes used specifically in environments where there's a lot of electromagnetic interference from outside sources.
