:PROPERTIES:
:ID:       b691522c-6f33-4e1d-96e2-88233ea5dcb4
:END:
#+title: .this reference
#+property: header-args :tangle code/java/this_reference.java

* Java =this= Reference

The keyword =this= refers to the *current (calling) object*.  
When an instance method is *invoked* on an ~object~, the =this= reference is automatically set to that object.

It allows the =method= or =constructor= to access the object's *instance variables / methods*.

The =this= reference is commonly used to:
- Refer to the current object's instance variables
- Distinguish *instance variables* from *local variables*
- Invoke another =constructor= in the same ~class~

* Referencing Instance Members

You can explicitly use =this= to reference instance variables and methods.

Example:

#+BEGIN_SRC java
public class Circle {

    double radius;

    public double getArea() {
        return Math.PI * this.radius * this.radius;
    }

    public void printArea() {
        System.out.println("Area: " + this.getArea());
    }

}
#+END_SRC

In this example:
- =this.radius= refers to the current object's radius
- =this.getArea()= explicitly calls the object's method

Often, =this= is omitted for brevity.

Example without =this=:

#+BEGIN_SRC java
public double getArea() {
    return Math.PI * radius * radius;
}
#+END_SRC

* Resolving Variable Shadowing

The =this= keyword is necessary when a method or constructor parameter has the *same name* as an instance variable.

Example:

#+BEGIN_SRC java
public class Circle {

    double radius;

    public Circle(double radius) {
        this.radius = radius;
    }

}
#+END_SRC

Explanation:
- The parameter =radius= hides the instance variable
- =this.radius= refers to the object's field
- =radius= refers to the constructor parameter

* Invoking Another Constructor

The =this()= syntax can call another constructor in the same class.

#+BEGIN_SRC java
public class Circle {

    double radius;

    public Circle() {
        this(1.0);
    }

    public Circle(double radius) {
        this.radius = radius;
    }

}
#+END_SRC

Here:
- =this(1.0)= calls the second constructor
- This technique is known as *constructor chaining*

* Key Points

- =this= refers to the *current object*
- It can reference instance variables and methods
- It helps resolve variable name conflicts
- It can invoke another constructor using =this()=
- It is often omitted when the meaning is clear
