:PROPERTIES:
:ID:       8af929df-eab6-4a08-a5ab-fcd7460923d7
:ROAM_ALIASES: DNS
:END:
#+title: Domain Name System (DNS)

Global and highly distributed network service that resolves strings of letters ([[id:99127e79-40d3-4e48-855b-94268667e239][Domain Name]]) into IP addresses for you.

Turns domain names into [[id:1011a8fb-ad00-40bb-a1cc-4b53c9fedff0][IP Addresses]], which allow browsers to get to websites and other internet resources.

This process is called [[id:3e540e6d-738f-4822-b69a-efe8cb0906a9][Name Resolution]].

[[id:a1f5402c-78da-4b9a-b620-823327ff6c0b][DNS TTL]]

* Primary Types of DNS
** 1. Caching Name Servers
(Provided by ISP)
Store known domain lookups for a certain amount of time.

** 2. Recursive Name Servers
(Provided by ISP)
Store known domain lookups for a certain amount of time.
Performs full [[id:8af929df-eab6-4a08-a5ab-fcd7460923d7][DNS]] resolution requests.

** 3. Root Name Servers
A name server for the root zone of the Domain Name System of the Internet.

** 4. [[id:d038356e-bc16-4910-8e1e-22c65d774fda][Top-Level Domain (TLD)]] Name Servers
[[id:e2102c67-5477-4920-bb3d-b9425718ad53][Anycast]]
** 5. Authoritative Name Servers


* [[id:287e1cc3-52af-4aba-86b1-a378e725315a][Resource Record Types]]

* [[id:6b8967d4-8919-46d9-b8d8-49c24464be4a][DNS Zones]]
