:PROPERTIES:
:ID:       978e88bf-bfac-4a29-a851-048441593c54
:END:
#+title: Comparable Interface

* Comparable Interface

- The =Comparable interface= defines the ~compareTo~ method for *comparing* *objects*.

Suppose you want to design a generic method to find the larger of two objects of the same type, such as two students, two dates, two circles, two rectangles, or two squares.

In order to accomplish this, the *two* ~objects~ must be *comparable*, so the common *behavior* for the ~objects~ must be *comparable*.

Java provides the *Comparable interface* for this purpose.

** Syntax

The *interface* is defined as follows:

#+BEGIN_SRC java
// Interface for comparing objects, defined in java.lang
package java.lang;

public interface Comparable<E> {
    public int compareTo(E o);
}
#+END_SRC

The ~compareTo~ method determines the *order* of this ~object~ with the specified ~object o~ and returns:
- A negative integer: Object is less than ~o~.
- Zero: Object is equal to ~o~.
- A positive integer: Object is greater than ~o~.

The =Comparable interface= is a *generic interface*.

The *generic* type ~E~ is replaced by a *concrete* type when *implementing* this *interface*.

Many classes in the Java library implement =Comparable= to define a natural order for objects.

The classes ~Byte, Short, Integer, Long, Float, Double, Character, BigInteger, BigDecimal, Calendar, String, and Date~ all *implement* the =Comparable interface=.

*** Example
For example, the ~Integer, BigInteger, String, and Date~ classes are defined as follows in the Java API:
#+BEGIN_SRC java
public final class Integer extends Number
    implements Comparable<Integer> {
        // class body omitted
        @override
        public int compareTo(Integer o){
            // Implementation mitted
    }
}
#+END_SRC

#+BEGIN_SRC java
public final class BigInteger extends Number
    implements Comparable<BigInteger> {
        // class body omitted
        @override
        public int compareTo(Integer o){
            // Implementation mitted
    }
}
#+END_SRC

#+BEGIN_SRC java
public final class String extends Object
    implements Comparable<String> {
        // class body omitted
        @override
        public int compareTo(String o){
            // Implementation mitted
    }
}
#+END_SRC

#+BEGIN_SRC java
public final class Date extends Object
    implements Comparable<Date> {
        // class body omitted
        @override
        public int compareTo(Date o){
            // Implementation mitted
    }
}
#+END_SRC

Thus, ~numbers~ are *comparable*, ~strings~ are *comparable*, and so are ~dates~.

You can use the ~compareTo~ method to *compare* two ~numbers~, two ~strings~, and two ~dates~.

**** Example

For example, the following code:

#+BEGIN_SRC java
System.out.println(Integer.valueOf(3).compareTo(5));
System.out.println("ABC".compareTo("ABC"));

java.util.Date date1 = new java.util.Date(2013, 1, 1);
java.util.Date date2 = new java.util.Date(2012, 1, 1);

System.out.println(date1.compareTo(date2));
#+END_SRC

***** Output

#+BEGIN_SRC java
−1 // Displays a negative value since 3 is less than 5.
0 // Displays zero since ABC is equal to ABC
1 // Displays a positive value since date1 is greater than date2
#+END_SRC

**** Example

Let ~n~ be an =Integer object=, s be a =String object=, and d be a =Date object=.

All the following expressions are *true*:

#+BEGIN_SRC java
n instanceof Integer
n instanceof Object
n instanceof Comparable

s instanceof String
s instanceof Object
s instanceof Comparable

d instanceof Date
d instanceof Object
d instanceof Comparable
#+END_SRC

The =Object class= contains the ~equals~ method, which is intended for the =subclasses= of the =Object class= to *override* in order to *compare* whether the *contents* of the ~objects~ are *the* *same*.

Since the ~compareTo~ method is *not* defined in the =Object class=, the *Comparable interface* is defined to enable ~objects~ to be *compared* if they are =instances= of the *Comparable interface*.

~compareTo~ should be *consistent* with ~equals~.

For two objects =o1= and =o2=, ~o1.compareTo(o2) == 0~ iff ~o1.equals(o2)~ is *true*.

Therefore, you should also *override* the ~equals~ method.
