:PROPERTIES:
:ID:       950c7641-c24d-4636-9527-e869c7c258a9
:END:
#+title: Inheriting Duplicate default Methods

* Inheriting Duplicate default Methods

If a class inherits *two or more* ~default methods~ with the same [[id:d50403a0-c944-4f72-bfb0-f9387796c6f5][method signature]], then the class *must* override the method.

** Example

#+BEGIN_SRC java
public interface Walk {
    public default int getSpeed() { return 5; }
}

public interface Run {
    public default int getSpeed() { return 10; }
}

public class Cat implements Walk, Run {} // DOES NOT COMPILE
#+END_SRC

In the above example, ~Cat~ *inherits* the two ~default methods~ for ~getSpeed()~, so which does it use?

Since ~Walk~ and ~Run~ are considered siblings in terms of how they are used in the ~Cat~ class, it is not clear whether the code should output =5= or =10=.
In this case, the *compiler* throws an *error*.

If the ~class~ implementing the ~interfaces~ *overrides* the *duplicate* default method, the code *will compile* without issue.
By *overriding* the *conflicting* method, the ambiguity about which version of the method to call has been removed.
For example, the following modified implementation of Cat will compile:

#+BEGIN_SRC java
public class Cat implements Walk, Run {
    public int getSpeed() { return 1; }
}
#+END_SRC
