:PROPERTIES:
:ID:       c5290b21-44d0-4a2b-ac7a-533a0171ac01
:END:
#+title: Computing History

* Computing History

** Mechanical Machines (before =1930=)

- [[id:5f1a7be8-3673-4ead-b491-b1fd65a064c8][Pascaline]]
- [[id:2393b3a8-d90a-4962-9d91-182d6f9e8fd2][Leibniz Wheel]]
- [[id:c835f120-2552-4c43-b7ef-13303b0841d8][Difference Engine]]
- [[id:d432f62d-8436-4492-b4fa-ef4fa5331c22][Analytical Engine]]
- [[id:619d9e09-673e-4d65-ad57-75085679520c][Herman Hollerith]]

** Electronic Computers (=1930-1950=)

- [[id:c7dd004e-cc7b-45dc-a962-c4ab72898045][Atanasoff Berry Computer (ABC)]]
- [[id:2e14052c-796b-475a-ae43-8a9ba5a2ac73][Z1]]
- [[id:a51b0a6d-7cef-449c-8e16-d8f8f7f5a32d][Mark 1]]
- [[id:d0fa831e-3a0a-4e0c-8bc4-0397ee4aec2a][Colossus]]
- [[id:b004bf6d-8030-4d9e-a2c3-b612111865ca][ENIAC]]

** Computer Generations (=1950-Present=)

Computers built after =1950= more or less follow the [[id:0dfb80a3-bb69-4347-a822-1227fece944a][von Neumann Model]]. (Storing data and the [[id:899ca310-9704-46b5-9177-b2d76a875456][program]] in memory)

*** First Generation (=1950-1959=)

Characterized by the emergence of commercial computers.

Computers were *bulky* and used *vacuum tubes* as electronic switches.

At this time, computers were affordable *only* by big organizations.

*** Second Generation (=1959-1965=)

Used transistors instead of vacuum tubes.

This reduced the size of computers, as well as their cost, and made them affordable to small and medium-size corporations.

Two high-level programming languages, [[id:0cb09013-1748-4014-b00b-9fed24f2fdf1][FORTRAN]] and [[id:f5621d16-9902-47ee-b992-e1381bb0c09c][COBOL]], were invented and made programming easier.

These two languages separated the programming task from the computer operation task.

*** Third Generation (=1965-1975=)

The invention of the integrated circuit (transistors, wiring, and other components on a single chip) reduced the cost and size of computers even further.

Minicomputers appeared on the market.

~Canned programs~, popularly known as software packages, became available.

*** Fourth Generation (=1975-1985=)

Saw the appearance of microcomputers.
[[id:66da5f43-460b-4c43-9a03-bf782167b278][Altair 8800]]
Advances in the electronics industry allowed whole computer subsystems to fit on a ~single circuit board~.

*** Fifth Generation (=1985=)

It has witnessed the appearance of ~laptop~ and ~palmtop~ computers, improvements in secondary storage media (CD-ROM, DVD, and
so on), the use of multimedia, and the phenomenon of virtual reality.
