:PROPERTIES:
:ID:       0526ffdf-bdb1-4f35-a65f-ef29391f84a3
:END:
#+title: Switch statements
#+filetags: :OCP:
#+property: header-args :tangle code/ocp/3/switch_statements.java

* Switch statements

** [[id:dff95a75-a51e-4286-bcd2-d35a04e45a2a][Switch Case]]

The following is a list of all ~data types~ supported by ~switch~ statements:
- ~int~ and ~Integer~
- ~byte~ and ~Byte~
- ~short~ and ~Short~
- ~char~ and ~Character~
- ~String~
- ~enum~ values
- ~var~ (if the type resolves to one of the preceding types)

#+BEGIN_SRC java
public void printDayOfWeek(int day) {
    switch(day) {
        case 0:
            System.out.print("Sunday");
            break;
        case 1:
            System.out.print("Monday");
            break;
        case 2:
            System.out.print("Tuesday");
            break;
        case 3:
            System.out.print("Wednesday");
            break;
        case 4:
            System.out.print("Thursday");
            break;
        case 5:
            System.out.print("Friday");
            break;
        case 6:
            System.out.print("Saturday");
            break;
        default:
            System.out.print("Invalid value");
            break;
    }
}
#+END_SRC

A ~break~ statement *terminates* the switch statement and returns flow control to the enclosing process.

** Rules
- The ~value1~, ~...~, and ~valueN~ must have the *same*** data type as the value of the =switch-expression=. Note that ~value1~, ~...~, and ~valueN~ are *constant* *expressions*, they cannot contain variables like ~1 + x~.
- When the value in a *case* statement matches the value of the =switch-expression=, the statements starting from this case are executed until either a *break* *statement* or the *end* of the *switch* statement is reached.
- The *default* *case* (optional) can be used to perform actions when *none* of the specified cases matches the =switch-expression=.
- The keyword *break* is *optional*. The *break* *statement* immediately *ends* the *switch* *statement*.

** _Exam trick_

*** [[id:da520312-7c4b-4921-a7e2-ac5d4ea280c8][Fall Through behaviour]]

Notice that ~boolean~, ~long~, ~float~, and ~double~ are excluded from switch statements, as are their associated Wrapper Classes.

The reasons are varied, such as ~boolean~ having *too small a range* of values and *floating­point* numbers having quite a *wide range of values*.

For the exam, though, you just need to know that they are *not* permitted in switch statements.

** Acceptable Case Values

Not just any variable or value can be used in a ~case~ statement.

You can use *only* ~literals~, ~enum~ ~constants~, or ~final constant variables~ of the *same* data type.

For example, you *can’t* have a ~case~ statement value that requires executing a method at runtime, even if that method always returns the same value.

For these reasons, only the *first* and *last* ~case~ statements in the following example compile:

#+BEGIN_SRC java
final int getCookies() { return 4; }

void feedAnimals() {
    final int bananas = 1;
    int apples = 2;
    int numberOfAnimals = 3;
    final int cookies = getCookies();

    switch(numberOfAnimals) {
    case bananas:
    case apples: // DOES NOT COMPILE
    case getCookies(): // DOES NOT COMPILE
    case cookies: // DOES NOT COMPILE
    case 3 * 5 :
    }
}
#+END_SRC

- The ~bananas~ variable is marked =final=, and its *value is known at compile­time*, so it is valid.

- The ~apples~ variable is *not* marked =final=, even though its value *is known*, so it is not permitted.

- The next two case statements, with values ~getCookies()~ and ~cookies~, do *not* compile because methods are not evaluated *until runtime*, so they cannot be used as the
  value of a case statement, *even if* one of the values is stored in a =final= variable.

- Next, the ~data type~ for case statements must match the ~data type~ of the ~switch~ variable.
For example, you can’t have a case statement of type ~String~ if the switch statement variable is of type ~int~, since the types are incomparable.
