:PROPERTIES:
:ID:       0a79945a-f107-4cba-85d0-4c824c6598e4
:END:
#+title: Calling Parent Constructors with super()
#+property: header-args :tangle code/ocp/6/calling_parent_constructors_with_super.java

* Calling Parent Constructors with super()

The first statement of every constructor is a call to a *parent* constructor using ~super()~ or *another* constructor in the class using [[id:6d0ddb05-83c3-4a23-bf52-9fab2633bd99][this()]].

- ~super()~ calls a *parent* constructor.

Unlike *properties* and *methods*, the *constructors* of a =superclass= are *not* inherited by a =subclass=.

They can only be *invoked* from the *constructors* of the =subclasses= using the keyword ~super~.

** Syntax

#+BEGIN_SRC java
super();
super(arguments);
#+END_SRC

- ~super()~ invokes the *no-arg constructor* of its =superclass=
- ~super(arguments)~ invokes the =superclass= *constructor* that matches the arguments.

*** Note

~super()~ or ~super(arguments)~ *must* be the *first* statement of the =subclass’s= *constructor*; this is the /only way/ to explicitly invoke a =superclass= *constructor*.

** Example

#+BEGIN_SRC java
public class Animal {
    private int age;

    public Animal(int age) {
        super(); // Refers to constructor in java.lang.Object
        this.age = age;
    }
}
#+END_SRC

#+BEGIN_SRC java
public class Zebra extends Animal {
    public Zebra(int age) {
        super(age); // Refers to constructor in Animal
    }
    public Zebra() {
        this(4); // Refers to constructor in Zebra with ~int~ argument
    }
}
#+END_SRC

** _Exam Trick_

Like calling [[id:6d0ddb05-83c3-4a23-bf52-9fab2633bd99][this()]], calling ~super()~ can only be used as the *first* statement of the *constructor*.

*** Example (Non callable)

#+BEGIN_SRC java
public class Zoo {
    public Zoo() {
        System.out.println("Zoo created");
        super(); // DOES NOT COMPILE
    }
}
public class Zoo {
    public Zoo() {
        super();
        System.out.println("Zoo created");
        super(); // DOES NOT COMPILE
    }
}
#+END_SRC

** Overloaded Parent Constructors

- If the ~parent class~ has more than one =constructor=, the ~child class~ may use any valid ~parent~ =constructor= in its definition.
  
*** Example

#+BEGIN_SRC java
public class Animal {
    private int age;
    private String name;

    public Animal(int age, String name) { // First Constructor
        super();
        this.age = age;
        this.name = name;
    }

    public Animal(int age) { // Second Constructor
        super();
        this.age = age;
        this.name = null;
    }
}

public class Gorilla extends Animal {
    public Gorilla(int age) {
        super(age,"Gorilla"); // Calls the first Animal constructor
    }
    public Gorilla() {
        super(5); // Calls the second Animal constructor
    }
}
#+END_SRC


*** _Exam Trick_

The [[id:d5b4004d-b5db-48a2-8e85-09359ca61a42][javac]] automatically inserts a call to the *no­argument* =constructor= ~super()~ if you do *not* explicitly call ~this()~ or ~super()~ as the first line of a constructor.

- The following three ~class~ and =constructor= definitions are equivalent, because the *compiler* will automatically convert them all to the last example.

**** Example

#+BEGIN_SRC java
public class Donkey {}

public class Donkey {
    public Donkey() {}
}

public class Donkey {
    public Donkey() {
        super();
    }
}
#+END_SRC

*** Syntax Error When Calling a Superclass Constructor by Name

- Invoking a =superclass= *constructor's* name directly inside a =subclass= causes a *syntax error*.
- In =Java=, *constructors* are *not inherited* and *cannot* be called like /normal methods/. (The keyword ~super~ *must* be used!)

**** Invalid Call

#+BEGIN_SRC java
class GeometricObject {
    public GeometricObject(String color, boolean filled) {
        System.out.println("GeometricObject constructor called");
    }
}

class Circle extends GeometricObject {

    public Circle(double radius, String color, boolean filled) {

        // Incorrect: calling superclass constructor by name
        GeometricObject(color, filled); // Syntax error

    }
}
#+END_SRC

**** Valid Call

The correct way to invoke the =superclass= constructor is with ~super(...)~:

#+BEGIN_SRC java
class Circle extends GeometricObject {

    public Circle(double radius, String color, boolean filled) {
        super(color, filled); // Correct
    }
}
#+END_SRC

** See also
*** [[id:55699fdc-5fdc-4c94-b8d7-7b4c230ad0c5][Constructor Chaining]]
