:PROPERTIES:
:ID:       5e09bcf0-2de5-4b84-a9ed-b3654bf0df40
:END:
#+title: Understanding Inheritance

* Understanding Inheritance

*Inheritance* is the process by which a =subclass= automatically includes certain members of the class, including primitives, objects, or methods, defined in the =parent= class.

We indicate a class is a =subclass= by declaring it with the ~extends~ keyword

** Example

#+BEGIN_SRC java
public class Mammal {} // Superclass
public final class Rhino extends Mammal {} // Subclass
#+END_SRC

** Transitive

One key aspect of *inheritance* is that it is *transitive*.

Given three classes ~[X, Y, Z]~, if ~X~ =extends= ~Y~, and ~Y~ =extends= ~Z~, then ~X~ is considered a =subclass= or =descendant= of ~Z~.

Likewise, ~Z~ is a =superclass= or =ancestor= of ~X~.

We sometimes use the term *direct* =subclass= or =descendant= to indicate the class *directly* extends the parent class.
For example, ~X~ is a *direct* =descendant= only of class ~Y~, *not* ~Z~.

** Access
When one class *inherits* from a =parent= class, all [[id:28127310-6300-4e4f-9935-8c2377e7de75][public]] and [[id:2085746a-5d79-403a-a417-5a0ef14f9933][protected]] members are automatically available as part of the =child= class.

If the two classes are in the *same* package, then package members *are available* to the child class.

Last but not least, [[id:0ea2ebdc-e6b9-405e-be35-ce90462279fe][private]]  members are restricted to the class they are defined in and are *never* available via *inheritance*.

** [[id:8e0bae56-3a80-4227-ad57-4c5fd3070cd5][Class Access Modifiers]]
** [[id:fd832390-4e2b-47c7-8d11-aeaa272a22b6][Inheriting The Object class]]
