:PROPERTIES:
:ID:       44a16f84-0d2c-4f42-8f51-d24f8985e648
:END:
#+title: Creating Simple Enums
#+property: header-args :tangle code/ocp/7/creating_simple_enums.java

* Creating Simple Enums

** Example

#+BEGIN_SRC java
public enum Season {
    Winter,
    SPRING,
    SUMMER,
    FALL; // Optional for Simple Enums
}
#+END_SRC

#+BEGIN_SRC java
var s = Season.SUMMER;

System.out.println(Season.SUMMER); // SUMMER
System.out.println(s == Season.SUMMER); // true
#+END_SRC

*** _Exam Trick_

Enums print the *name* of the enum when ~toString()~ is called.

They can be compared using ~==~ because they are like static final constants.

In other words, you can use ~equals()~ or ~==~ to compare enums, since each enum value is initialized only once in the JVM.

** Calling the values(), name(), and ordinal() Methods

*** values()

An enum provides a ~values()~ method to get an ~array~ of all of the *values*.

#+BEGIN_SRC java
for(var season: Season.values()) {
    System.out.println(season.name() + " " + season.ordinal());
}
/*
 * OUTPUT:
 * WINTER 0
 * SPRING 1
 * SUMMER 2
 * FALL 3
*/
#+END_SRC

*** valueOf()

Another useful feature is retrieving an enum ~value~ from a ~String~ using the ~valueOf()~ method.

This is helpful when working with older code or parsing user input.

The ~String~ passed in must match the enum ~value~ *exactly*, though.

**** Example

The =first= statement works and assigns the proper enum value to ~s~.
Note that this line is not creating an enum value, at least not directly.

Each enum value is created once when the enum is first loaded.

Once the enum has been loaded, it retrieves the single enum value with the matching name.

#+BEGIN_SRC java
Season s = Season.valueOf("SUMMER"); // SUMMER
Season t = Season.valueOf("summer"); // IllegalArgumentException
#+END_SRC

The =second= statement encounters a problem.
There is no enum value with the lowercase name ~summer~. (throws an =IllegalArgumentException=)

#+BEGIN_SRC java
Exception in thread "main" java.lang.IllegalArgumentException:
No enum constant enums.Season.summer
#+END_SRC
