:PROPERTIES:
:ID:       6d0ddb05-83c3-4a23-bf52-9fab2633bd99
:END:
#+title: Calling overloaded Constructors with this()
#+property: header-args :tangle code/ocp/6/overloaded_constructors_with_this.java

* Calling overloaded Constructors with this()

Since a ~class~ can contain *multiple overloaded* =constructors=, these =constructors= can actually call one another!

** Example

One of the constructors takes a single ~int~ parameter.
The other takes an ~int~ and a ~String~.

These [[id:94f7186e-22e8-4636-bc8c-a4cc040d9073][parameter lists]] are different, so the ~constructors~ are successfully *overloaded*.

There is a bit of duplication, as ~this.weight~ is assigned the same way in both constructors.

In programming, even a bit of duplication tends to turn into a lot of duplication as we keep adding “just one more thing.”

For example, imagine that we have five variables being set like ~this.weight~, rather than just one.

#+BEGIN_SRC java
public class Hamster {
    private String color;
    private int weight;

    public Hamster(int weight, String color) { // First constructor
        this.weight = weight;
        this.color = color;
    }

    public Hamster(int weight) { // Second constructor
        this.weight = weight;
        color = "brown";
    }
}
#+END_SRC

*** Solution

What we really want is for the *first* ~constructor~ to *call* the *second* ~constructor~ with two parameters.

When ~this()~ is used *with parentheses*, Java calls *another constructor* on the *same* instance of the ~class~.

#+BEGIN_SRC java
public class Hamster {
    private String color;
    private int weight;

    public Hamster(int weight, String color) { // First constructor
        this.weight = weight;
        this.color = color;
    }

    public Hamster(int weight) {
        this(weight, "brown");
    }
}
#+END_SRC

*** _Exam Trick_

Calling ~this()~ has one special rule you need to know.
If you choose to call it, the ~this()~ call must be the *first* statement in the ~constructor~.

The side effect of this is that there can be *only one* call to ~this()~ in any constructor.

#+BEGIN_SRC java
public Hamster(int weight) {
    System.out.println("chew");
    // Set weight and default color
    this(weight, "brown"); // DOES NOT COMPILE
}
#+END_SRC

*** Infinite Cycle (Cyclic)

#+BEGIN_SRC java
public class Gopher {
    public Gopher(int dugHoles) {
        this(5); // DOES NOT COMPILE
    }
}
#+END_SRC

*** Rules

- A ~class~ can contain *many* overloaded constructors, provided the signature for each is *distinct*.
- The compiler inserts a *default* no­argument ~constructor~ if no ~constructors~ are declared.
- If a constructor calls ~this()~, then it must be the *first line* of the constructor.
- Java does not allow *cyclic* constructor calls.
