:PROPERTIES:
:ID:       c67b24a4-82f7-4423-83a9-75fc1c566166
:END:
#+title: Overriding a Method

* Overriding a Method

*Overriding* a ~method~ occurs when a ~subclass~ declares a new implementation for an inherited method with the *same signature and compatible return type*.


** Example

When you *override* a method, you may still =reference= the ~parent~ version of the method using the ~super~ keyword.

In this manner, the keywords ~this~ and ~super~ allow you to select between the *current* and *parent* versions of a method, respectively

#+BEGIN_SRC java
public class Marsupial {
    public double getAverageWeight() {
        return 50;
    }
}

public class Kangaroo extends Marsupial {
    public double getAverageWeight() {
        return super.getAverageWeight() + 20;
    }
    public static void main(String[] args) {
        System.out.println(new Marsupial().getAverageWeight()); // 50.0
        System.out.println(new Kangaroo().getAverageWeight()); // 70.0
    }
}
#+END_SRC

*** Rules
1. The method in the ~child~ class must have the *same signature* as the method in the ~parent~ class.
2. The method in the ~child~ class must be at least as *accessible* as the method in the ~parent~ class.
3. The method in the ~child~ class may not declare a *checked exception* that is new or broader than the class of any exception declared in the ~parent~ class method.
4. If the method returns a value, it must be the ~same~ or a ~subtype~ of the method in the ~parent~ class, known as [[id:6da516df-94e4-4b63-a787-0bddd7e6c6ca][Covariant Return Types]].
