:PROPERTIES:
:ID:       029f5f49-3afe-4d54-ac77-e3963bce5ee6
:END:
#+title: Default Constructor

* Default Constructor
#+property: header-args :tangle code/ocp/6/default_constructor.java

Every class in Java has a ~constructor~, whether you code one or not.
If you don’t include any ~constructors~ in the class, Java will create one for you without any parameters.

This Java­created ~constructor~ is called the *default constructor* and is added any time a class is declared without any constructors.

We often refer to it as the default ~no­argument constructor~, for clarity.

The =default constructor= has an empty [[id:94f7186e-22e8-4636-bc8c-a4cc040d9073][parameter list]] and an *empty body*.

** Example (Compiler Created)

In the ~Rabbit~ class, Java sees that no constructor was coded and creates one:

#+BEGIN_SRC java
public class Rabbit {
    public static void main(String[] args) {
        new Rabbit(); // Calls the default constructor
    }
}
#+END_SRC

** Example (User Defined)

In the ~Rabbit~ class, Java sees that no constructor was coded and creates one:

#+BEGIN_SRC java
public class Rabbit {
    public Rabbit(){}
    public static void main(String[] args) {
        new Rabbit(); // Calls the user-defined constructor
    }
}
#+END_SRC

** _Exam Trick_

For the exam, one of the most important rules you need to know is that the =compiler= *only* inserts the ~default constructor~ when *no* ~constructors~ are defined.

Having only *private* ~constructors~ in a class tells the compiler *not to* provide a ~default no­argument constructor~.

It also *prevents* other ~classes~ from *instantiating* the ~class~.

This is useful when a class has only [[id:71f8ac46-9cca-4866-b701-8f5a7f9f7fc0][static methods]] or the developer wants to have full control of all calls to create *new instances* of the ~class~.

** [[id:68584fc1-3dde-48e5-badb-67d43e5e875a][Default Constructor Tips and Tricks]]
