:PROPERTIES:
:ID:       0a79945a-f107-4cba-85d0-4c824c6598e4
:END:
#+title: Calling Parent Constructors with super()
#+property: header-args :tangle code/ocp/6/calling_parent_constructors_with_super.java

* Calling Parent Constructors with super()

The first statement of every constructor is a call to a *parent* constructor using ~super()~ or *another* constructor in the class using [[id:6d0ddb05-83c3-4a23-bf52-9fab2633bd99][this()]].

~super()~, calls a *parent* constructor.

** Example

#+BEGIN_SRC java
public class Animal {
    private int age;

    public Animal(int age) {
        super(); // Refers to constructor in java.lang.Object
        this.age = age;
    }
}
#+END_SRC

#+BEGIN_SRC java
public class Zebra extends Animal {
    public Zebra(int age) {
        super(age); // Refers to constructor in Animal
    }
    public Zebra() {
        this(4); // Refers to constructor in Zebra with ~int~ argument
    }
}
#+END_SRC

** _Exam Trick_

Like calling [[id:6d0ddb05-83c3-4a23-bf52-9fab2633bd99][this()]], calling ~super()~ can only be used as the *first* statement of the constructor.

*** Example (Non callable)

#+BEGIN_SRC java
public class Zoo {
    public Zoo() {
        System.out.println("Zoo created");
        super(); // DOES NOT COMPILE
    }
}
public class Zoo {
    public Zoo() {
        super();
        System.out.println("Zoo created");
        super(); // DOES NOT COMPILE
    }
}
#+END_SRC

** Overloaded Parent Constructors

*** Example

If the ~parent class~ has more than one =constructor=, the ~child class~ may use any valid ~parent~ =constructor= in its definition:

#+BEGIN_SRC java
public class Animal {
    private int age;
    private String name;

    public Animal(int age, String name) { // First Constructor
        super();
        this.age = age;
        this.name = name;
    }

    public Animal(int age) { // Second Constructor
        super();
        this.age = age;
        this.name = null;
    }
}

public class Gorilla extends Animal {
    public Gorilla(int age) {
        super(age,"Gorilla"); // Calls the first Animal constructor
    }
    public Gorilla() {
        super(5); // Calls the second Animal constructor
    }
}
#+END_SRC


*** _Exam Trick_

The [[id:d5b4004d-b5db-48a2-8e85-09359ca61a42][javac]] automatically inserts a call to the *no­argument* =constructor= ~super()~ if you do *not* explicitly call ~this()~ or ~super()~ as the first line of a constructor.

For example, the following three ~class~ and =constructor= definitions are equivalent, because the *compiler* will automatically convert them all to the last example.

**** Example

#+BEGIN_SRC java
public class Donkey {}

public class Donkey {
    public Donkey() {}
}

public class Donkey {
    public Donkey() {
        super();
    }
}
#+END_SRC
