:PROPERTIES:
:ID:       d8e80e73-e1b7-4732-8f4b-b72e0169b64e
:END:
#+title: Local Variable Modifiers
#+property: header-args :tangle code/ocp/5/local_variable_modifiers.java

* Local Variable Modifiers

There’s only one modifier that can be applied to a local variable: ~final~
When writing ~methods~, developers may want to set a variable that *does not change* during the course of the method.

** _Exam Trick_

As shown with the ~rest~ variable, we don’t *need* to assign a value when a final variable is *declared*.
The rule is only that it *must be assigned* a value *before it can be used*.

*** Example

#+BEGIN_SRC java
public void zooAnimalCheckup(boolean isWeekend) {
    final int rest;
    if(isWeekend) rest = 5; else rest = 20;
    System.out.print(rest);

    final var giraffe = new Animal();
    final int[] friends = new int[5];

    rest = 10; // DOES NOT COMPILE
    giraffe = new Animal(); // DOES NOT COMPILE
    friends = null; // DOES NOT COMPILE
}
#+END_SRC

*** Bad Example
The ~rest~ variable might not have been assigned a value, such as if ~isWeekend~ is =false=.
Since the compiler does not allow the use of local variables that *may not* have been assigned a value, the code does *not compile*.

#+BEGIN_SRC java
public void zooAnimalCheckup(boolean isWeekend) {
    final int rest;
    if(isWeekend) rest = 5;
    System.out.print(rest); // DOES NOT COMPILE (rest is Potentially not assigned a value)
}
#+END_SRC

*** Does using the final modifier mean we can’t modify the data?

*Nope*.
The ~final~ attribute only refers to the =variable reference=; the contents can be freely modified (assuming the object *isn’t immutable*).

#+BEGIN_SRC java
public void zooAnimalCheckup() {
    final int rest = 5;
    final Animal giraffe = new Animal();
    final int[] friends = new int[5];

    giraffe.setName("George"); // Allowed
    friends[2] = 2; // Allowed
}
#+END_SRC

The ~rest~ variable is a [[id:46582863-7f97-448d-bbc7-f7da4c1e7574][primitive]], so it’s just a value that *can’t* be modified.

On the other hand, the contents of the ~giraffe~ and ~friends~ variables *can* be freely modified, provided the variables aren’t reassigned.
