:PROPERTIES:
:ID:       08418523-7960-4d14-acd5-8fbc9cb143e8
:END:
#+title: Default Interface method
#+property: header-args :tangle code/ocp/7/default_interface_method.java

* Default Interface method

A ~default method~ is a method defined in an interface with the ~default~ keyword and *includes* a =method body=.

It may be *optionally* overridden by a ~class~ implementing the interface.

One use of ~default methods~ is for backward compatibility.

You can add a new ~default method~ to an ~interface~ without the need to modify all of the existing ~classes~ that *implement* the ~interface~.

The older ~classes~ will just use the ~default~ implementation of the method defined in the ~interface~.

This is where the name default method comes from!

** Example

The following is an example of a ~default method~ defined in an ~interface~:

#+BEGIN_SRC java
public interface IsColdBlooded {
    boolean hasScales();

    default double getTemperature() {
        return 10.0;
    }
}
#+END_SRC

This example defines two ~interface~ methods, one ~abstract~ and one ~default~.
The following ~Snake~ class, which implements ~IsColdBlooded~, *must* implement ~hasScales()~.

It may rely on the ~default~ implementation of ~getTemperature()~ or *override* the method with its own version:


#+BEGIN_SRC java
public class Snake implements IsColdBlooded {
    public boolean hasScales() { // Required override
        return true;
    }

    public double getTemperature() { // Optional override
        return 12;
    }
}
#+END_SRC

** Rules
For the exam, you should be familiar with various rules for declaring default methods.
Default Interface Method Definition Rules

1. A ~default method~ may be declared only within an ~interface~.
2. A ~default method~ must be marked with the ~default~ keyword *and include* a =method body=.
3. A ~default method~ is implicitly ~public~.
4. A ~default method~ *cannot* be marked ~abstract~, ~final~, or ~static~.
5. A ~default method~ *may be overridden* by a class that implements the ~interface~.
6. [[id:950c7641-c24d-4636-9527-e869c7c258a9][Inheriting Duplicate default Methods]]
