:PROPERTIES:
:ID:       e894bd80-a2dd-4749-a726-0fa1f2285e97
:END:
#+title: Lesson 3 Connect to the customer
#+filetags: :SAFe

* 3.1 Apply Customer centricity and design thinking
Design thinking is a customer centric development process
Customer-Centric organizations deliver solutions that are designed with a deep understanding of customer needs.

** Personas
Personas are fictional characters that represent the different people who might use your product.

- Personas convey the problems they're facing in context and key triggers for using the product.
- Capture rich, concise information that inspires great products without unnecessary details.

** Empathy Map
Used to identify with Customers.
- Empathy Map is a tool that helps teams develop deep, shared understanding and empathy for the customer.
- Use it to design better user Experiences and value streams.

* 3.2 Recognize product vision and roadmaps
** Vision alignes everyone on the product's direction
The product vision is a description of the future state of the product.
- How will the product solve our customer's problems?
- What features does it have?
- How will it differentatie us?
- What Non-Functional requirements (NFR) does it deliver?

** Roadmaps forecast upcoming work to realize the product vision
- Hierarchical Roadmaps provide multiple planning horizions
- Roadmaps communicate intent without over-constraining the implementation.

** Architectural Runway supports vision execution
Enables build up the runway
Features consume it

*** Intentional architecture
Fosters team alignment and defines the Architectural Runway.

*** Emergent design
Teams grow the system design as User Stories require

A balance between intentional architeture and emergent  design is required for speed of development and maintainability.
- Every team deserves to see the bigger picture
- Every team is empowered to design their part.



* 3.3 Define the work of customer
** Features represent the work for the ART

- Feature benefit hypothesis justifies development cost, customer value, and provides business perspective for decision making.
- Features contain acceptance criteria typically defined as part of refining the ART backlog.
- They reflect  functional and nonfunctional requirements.
- Features can be completed within a PI timebox.

** Teams break down features into User stories and Enabler stories
User stores are short descriptions of a small piece of desired functionality, written in the user's language.
Recommended form of expression is the user-voice form:
As a (user role), I want to (activity), so that (business value).

(I)ndependant
(N)egotiable
(V)aluable
(E)stimable
(S)mall
(T)estable

** Writing Good stories
- Card
- Conversation
- Confirmation

** Enabler stories
Enabler stories build the groundwork for future User Stories.
Four types of enabler stories:
- Infrastructure
- Architecture
- Exploration
- Compliance
