:PROPERTIES:
:ID:       23650ef0-bfe2-4e2f-b7c0-fd0218c4f01e
:END:
#+title: Lesson 6 Get Feedback
#+filetags: :SAFe

* 6.1 Getting customer feedback
** Connect to the customer:
- Product roles as a proxy (Understand customer's needs)
- Gemba walks (observing customers in day-to-day using solutions, obeserving problem spaces)
- Empathy mapping (Ability to put aside our preconceived ideas and develop solutions from the perspective of our customers)
  Tool that helps teams develop deep, shared understanding and empathy for others.
  Empathy map can be used to design better experiences and value streams.
- System Demo

* 6.2 Demonstrating value with Iteration Review
Demonstrating a working tested team increment
Iteration review provides true measure of progress by showing working software functionality and business outcome progression.

- Preparation starts with planning
- Teams demonstrate every Store, spike, refactor and NFR
- Attended by the team and stakeholders

1 - 2 hours

Two views from the iteration review based on a working system:
- How did we do in the iteration?
- How are we doing in the PI?

Cumulative Flow Diagrams (CFDs)

* 6.3 System Demo
Base milestones on objective evaluation of working systems

- Demos happen after iteration review and may lag by one iteration at most.
- Features are functionally complete.
- New features work together and with existing functionality.
- Demos happen from a staging enviornment that resembles production as much as possible.

Demonstrates value at each iteration
- System demo tests and evaluates the full solution in a production-like context, often through staging, to receive feedback from stakeholders.
