:PROPERTIES:
:ID:       049093ad-96f5-491e-a3d9-b80f757109ab
:END:
#+title: Bits and Bytes

A computer is really nothing more than a *series* of *switches*.

Each switch exists in two states: ~on~ or ~off~.

Storing information in a computer is simply a matter of setting a sequence of switches ~on~ or ~off~.

If the switch is on, its value is 1. If the switch is off, its value is 0.

These 0s and 1s are interpreted as digits in the binary number system and are called [[id:1c395ba6-27ab-4f09-beed-34f58f2ad557][Bits]] (binary digits).

The minimum storage unit in a computer is a [[id:14267f9e-5fe8-441f-8e3a-3c77d5868bd0][Byte]].

A small number such as ~3~ can be stored as a *single byte*.

To store a number that cannot fit into a *single* *byte*, the computer uses *several* *bytes*.

Data of various kinds, such as numbers and characters, are encoded as a series of bytes.

As a programmer, you don’t need to worry about the encoding and decoding of data, which the computer system performs automatically, based on the [[id:ef328551-cd74-449c-95c5-fef9ae9b7579][Encoding Scheme]].

In the popular [[id:84487ca4-e3fd-4ed6-b0b2-b51836993077][ASCII]] encoding scheme, for example, the character ~'C'~ is represented as *01000011* in *1* *byte*.

A computer’s storage capacity is measured in *bytes* and *multiples* of the *byte*, as follows:
- A ~kilobyte~ (~KB~) is about *1,000 bytes*.
- A ~megabyte~ (~MB~) is about *1 million bytes*.
- A ~gigabyte~ (~GB~) is about *1 billion bytes*.
- A ~terabyte~ (~TB~) is about *1 trillion bytes*.

A typical one-page word document might take ~20 KB~.

Therefore, ~1 MB~ can store *50* *pages* of documents, and ~1 GB~ can store *50,000* pages of documents.
A typical two-hour high resolution movie might take ~8 GB~, so it would require *160* *GB* to store 20 movies.
