:PROPERTIES:
:ID:       4eeadf74-8cef-4276-85a3-5865e0892c7e
:END:
#+title: Peer Reviews

The framework outlined below is a great guide on how to provide constructive feedback for peer review assignments on Coursera.

Providing strong feedback will help to encourage a culture of strong feedback!

*F.A.S.T* feedback
Strong feedback has 4 characteristics:

- Feed-forward
- Actionable
- Succinct
- Timely

A note about tone: Begin your feedback with at least one positive comment.

Be respectful and constructive by starting out with positive feedback before giving your critical feedback.

* Feed-forward:
Feed-forward feedback tells learners how your feedback will help them succeed in future assignments or reach their goals related to what is coming up in class.
Feed-forward feedback is focused on goals and the future. That’s why it’s important to give learners a forward reference point.

** Feed-forward feedback examples

- Implementing this feedback will help you do better on the next peer review assignment.
- Making these changes will help you code faster, so you will be a more efficient programmer.

** Not feed-forward feedback examples

- Think about this feedback carefully.
- You should make these changes.

* Actionable:
Feedback should be specific, useful, and provide actionable information.

For example, saying “good job!” or “you didn’t follow the instructions” are not actionable or useful.

What specifically should the learner do more or less of next time?

It might help to cite specific content from the learner’s submission.

** Actionable feedback examples
- I like how you answered the question in two paragraphs, as the instructions asked for. One way to improve it can be….
- Please limit your answer to 2 paragraphs of 5-8 sentences each.
- Your charts convey all the required information. It can be made more readable by changing the axis limits.
- You commented on the business’s financial position but did not include supporting data. Include specific profitability and liquidity data to support your argument.
** Not actionable feedback examples
- Good job!
- This is too long.
- Your chart isn't very clear.
- Your argument isn’t strong. It’s not very clear.

* Succinct:
Pick 2 or 3 key pieces of feedback that learners should focus on.

Change based on this feedback should make a significant, positive difference in their next draft.

* Timely:
The sooner the feedback, the better.

Feedback should ideally be given within *one* day and no longer than *2* *days* *after submission*.

** Timely feedback example
- *Within* 1 day of submission
** Somewhat timely feedback example
- 1-2 days *after* submission
** Not timely feedback example
- A week *after* submission
