:PROPERTIES:
:ID:       89797854-0fbd-4965-b7d5-d21570c7d45c
:END:
#+title: Super-Classes and Sub-Classes

* Super-Classes and Sub-Classes

In Java terminology, a class =C1= *extended* from *another* class =C2= is called a *subclass*, and =C2= is called a *superclass*.

- *superclass* / *parent class / *base class*.
- *subclass* / *child class* / *extended class* / *derived class*.

A =class= defines a *type*.

A *type* defined by a *subclass* is called a =subtype=, and a *type* defined by its *superclass* is called a =supertype=.

- =GeometricObject= is a ~supertype~ for =Circle=.
- =Circle= is a ~subtype~ of =GeometricObject=,

The *subclass* and its *superclass* are said to form a ~is-a~ relationship.

- A =Circle= *is a* =GeometricObject=.
- A =Rectangle= *is a* =GeometricObject=.

** Circle

- Inherits all accessible data *fields* and *methods* from the =GeometricObject= class.
- In addition, it has a new data field, =radius=, and its associated *getter* and *setter* methods.
- Also contains the ~getArea()~, ~getPerimeter()~, and ~getDiameter()~ methods.

** Rectangle

- Inherits all accessible data *fields* and *methods* from the =GeometricObject= class.
- In addition, it has the data fields =width= and =height= and their associated *getter* and *setter* methods.
- Also contains the ~getArea()~ and ~getPerimeter()~ methods.

** Code

*** Parent 

#+BEGIN_SRC java
public class GeometricObject {
    private String color = "white";
    private boolean filled;
    private java.util.Date dateCreated;

    // Construct a default geometric object
    public GeometricObject() {
        dateCreated = new java.util.Date();
    }

    /*
     * Construct a geometric object with the specified
     * color and filled value
     */
    public GeometricObject(String color, boolean filled) {
        dateCreated = new java.util.Date();
        this.color = color;
        this.filled = filled;
    }

    // Return color
    public String getColor() {
        return color;
    }

    // Set a new color
    public void setColor(String color) {
        this.color = color;
    }

    /*
     * Return filled.
     * Since filled is a boolean, its getter method is named isFilled
     */
    public boolean isFilled() {
        return filled;
    }

    // Set a new filled
    public void setFilled(boolean filled) {
        this.filled = filled;
    }

    // Get dateCreated
    public java.util.Date getDateCreated() {
        return dateCreated;
    }

    // Return a string representation of this Object
    public String toString() {
        return "created on " + dateCreated + "\ncolor: " + color + " and filled: " + filled;
    }
}
#+END_SRC

**** Child

#+BEGIN_SRC java
public class Circle extends GeometricObject {
    private double radius;

    public Circle() {

    }

    public Circle(double radius) {
        this.radius = radius;
    }

    public Circle(double radius, String color, boolean filled) {
        this.radius = radius;
        setColor(color);
        setFilled(filled);
    }

    public double getRadius() {
        return radius;
    }

    public void setRadius(double radius) {
        this.radius = radius;
    }

    public double getArea() {
        return radius * radius * Math.PI;
    }

    public double getDiameter() {
        return 2 * radius;
    }

    public double getPerimeter() {
        return 2 * radius * Math.PI;
    }

    public void printCircle() {
        System.out.println("The circle is created " + getDateCreated() + " and the radius is " + radius);
    }
}
#+END_SRC

- The ~extends~ *keyword* tells the compiler that =Circle= *extends* =GeometricObject=, thus *inheriting* the methods:
  - ~getColor~
  - ~setColor~
  - ~isFilled~
  - ~setFilled~
  - ~toString~

- The overloaded constructor ~Circle(double radius, String color, boolean filled)~ is *implemented* by invoking the ~setColor~ and ~setFilled~ methods (to set the ~color~ and ~filled~ properties).
- The *public methods* defined in the ~superclass~ =GeometricObject= are *inherited* in =Circle=, so they /can/ be used in the =Circle= class.
