:PROPERTIES:
:ID:       ea86c8e8-5b60-4bc8-aa74-f062c9848ffe
:END:
#+title: Lists

A list is an ordered sequence of data.

Each data item stored in a list is called an element.

In JavaScript, the elements of a list can be of any data type.

There is no predetermined number of elements that can be stored in a list (though the practical limit will be the amount of memory available to the program using the list).

A list with no elements is an *empty* list.

The number of elements stored in a list is called the ~length~ of the list.

Internally, the number of elements in a list is kept in a ~listSize~ variable.

You can append an element to the end of a list, or you can insert an element into a list after an existing element or at the beginning of a list.

Elements are deleted from a list using a *remove* operation.

You can also *clear* a list so that *all* of its current elements are removed.

Lists have properties to describe *location*.

There is the ~front~ of a list and the ~end~ of a list.

You can move from one element of a list to the *next* element using the ~next()~ operation.
You can move *backward* through a list using the ~prev()~ operation.

You can also move to a numbered position in a list using the ~moveTo(n)~ operation, where ~n~ specifies the *position* to move to.
The ~currPos~ property indicates the *current* *position* in a list.

* List ADT
| Name        | Type     | Description                                             | Time Complexity |
|-------------+----------+---------------------------------------------------------+-----------------|
| listSize    | Property | Number of elements in the list                          | O(1)            |
| pos         | Property | Current position in the list                            | O(1)            |
| length      | Property | Returns the number of elements in the list              | O(1)            |
| clear       | Function | Clears all elements from the list                       | O(n)            |
| toString    | Function | Returns string representation of the list               | O(n)            |
| getElement  | Function | Returns element at the current position                 | O(1)            |
| insert      | Function | Inserts new element after existing element              | O(n)            |
| append      | Function | Adds new element to the end of the list                 | O(1) amortized  |
| remove      | Function | Removes an element from the list                        | O(n)            |
| front       | Function | Sets current position to the first element              | O(1)            |
| end         | Function | Sets current position to the last element               | O(1)            |
| prev        | Function | Moves current position back one element                 | O(1)            |
| next        | Function | Moves current position forward one element              | O(1)            |
| currPos     | Function | Returns the current position in the list                | O(1)            |
| moveTo      | Function | Moves the current position to a specified position      | O(1)            |
