:PROPERTIES:
:ID:       25824dca-cd38-447d-84fd-8c69f246709f
:END:
#+title: Unicode

* Unicode

An [[id:ef328551-cd74-449c-95c5-fef9ae9b7579][encoding scheme]] established by the ~Unicode Consortium~ to support the *interchange*, *processing*, and *display* of written texts in the world’s diverse languages.

=Unicode= was originally designed as a 16-bit character encoding.

The primitive data type =char= was intended to take advantage of this design by providing a simple data type that could hold any character.

However, it turned out that the ~65,536~ characters possible in a =16-bit= *encoding* are not sufficient to represent *all* the =characters= in the world.

The *Unicode* *standard* therefore has been extended to allow up to ~1,112,064~ characters.

Those characters that go beyond the *original* =16-bit= limit are called *supplementary* *characters*.

Stored in a =char= *type* variable.

** Example

A =16-bit= Unicode takes *two* *bytes*, preceded by ~\u~, expressed in *four* *hexadecimal* *digits* that run from ~\u0000~ to ~\uFFFF~.
