:PROPERTIES:
:ID:       e30fcd5f-e6e3-47ca-9185-f3752dd9b81d
:END:
#+title: Java

* Java

** Origin
Originally called =Oak=.

Developed by a team led by *James Gosling* at ~Sun Microsystems~.

~Sun Microsystems~ purchased by ~Oracle~ in 2010.

=Java= was designed in *1991* for use in *embedded* *chips* in *consumer* *electronic* *appliances*.

In 1995, renamed Java, it was redesigned for developing web applications.

=Java= has become enormously popular.

Its rapid rise and wide acceptance can be traced to its design characteristics, particularly its promise that you can *write a program once and run it anywhere*.

As stated by its designer =Java= is:
- Simple
- [[id:991a3500-bb0e-4521-9c9c-bc66b537e427][Object Oriented]]
- Distributed
- Interpreted
- Robust
- Secure
- Architecture neutral
- Portable
- High performance
- Multithreaded
- Dynamic

=Java= is a *full-featured, general-purpose programming language* that can be used to develop robust mission-critical applications.

It is employed not only on *desktop* computers, but also on *servers* and *mobile* *devices*.

~More than 3 billion devices run Java~.

Most server-side applications were developed using Java.

The software for Android cell phones is developed using Java.

Java initially became attractive because Java programs can run from a web browser (applets).

Today applets are no longer allowed to run from a Web browser due to security issues.

=Java= is very popular for developing applications on *web servers*.

These applications *process* *data*, *perform* *computations*, and *generate* *dynamic* *webpages*.

** [[id:dc335c4f-f9e6-402c-b03c-f021488325cf][Java Language Spec]]

** [[id:37f8f6eb-3117-4dee-9b01-194e9d560111][Java Editions]]
