:PROPERTIES:
:ID:       9686bd39-ecc8-4867-8827-a2bbfb683dcb
:END:
#+title: Common Errors

* Common Errors

** 1: Undeclared/Uninitialised variables and unused variables
Forgetting to *declare* or *initialise* variables can cause ~compilation~ errors or ~unexpected~ ~behaviour~.

*Unused* variables clutter the code.

Consider the code below.

~double interestRateLoan = 0.05;~
~double interest = interestrateloan * 45;~

This code will fail to *compile* because the variables =interestrateloan= and =interestRateLoan= are different variables.

The example below comes from a previous worked solution.

However, one variable has not been *initialised*. See if you can spot it. Then select Run to check your answer.

** 2: Integer overflow
*Integer* *overflow* occurs when a calculation exceeds the =storage= limit of an ~integer~ type, leading to incorrect results.

This error can be critical in applications that require high precision, such as financial software or simulations.

~int value = 2147483647 + 1;  // value will actually be -2147483648~

** 3: Round-off errors
It is important to understand why =round-off= *errors* occur to ensure that you use the *correct* *data* *type* when performing calculations that require a high degree of precision.

Round-off errors occur when using [[id:8487dd79-f6a8-49d9-ba32-9b97c5056ef2][floating-point numbers]] due to their *limited* *precision*.

These errors are common in scientific and financial institutions and can lead to inaccurate outcomes.

~System.out.println(1.0 - 0.1 - 0.1 - 0.1 - 0.1 - 0.1);~
~System.out.println(1.0 - 0.9);~

** 4: Unintended integer division
Dividing =integers= results in an =integer= value, *truncating* the ~decimal~ part.

This often leads to incorrect results if [[id:8487dd79-f6a8-49d9-ba32-9b97c5056ef2][floating point]] division is *intended*.

** 5: Redundant input objects
Creating multiple redundant input objects (e.g. Scanner) for the same input source can cause unexpected behaviour, such as input skipping or errors.

It also wastes resources and reduces program efficiency.

#+BEGIN_SRC java
public class RedundantInputObject {
  public static void main(String[] args) {
    Scanner input = new Scanner(System.in);
    System.out.print("Enter an integer: ");
    int v1 = input.nextInt();

    Scanner input1 = new Scanner(System.in);
    System.out.print("Enter a double value: ");
    double v2 = input1.nextDouble();
  }
}

#+END_SRC
