:PROPERTIES:
:ID:       e75302ec-151f-4565-bd6b-12eadc2e29de
:END:
#+title: Hello World (Java)

* Hello World (Java)

#+BEGIN_SRC java
public class main {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
#+END_SRC


** Line 1
Line 1 defines a class.

Every Java program must have at least one class.

Each class has a name.

By convention, class names start with an uppercase letter.

In this example, the class name is =Welcome=.

** Line 2

Line 2 defines the =main= method.

The program is *executed* from the =main= method. (Entry Point)

A method is a construct that contains statements.

The main method in this program contains the ~System.out.println~ statement.

This statement displays the string =Hello, World!= on the console (line 4).

String is a programming term meaning a sequence of characters.

A string must be enclosed in *double* quotation marks.

Every statement in Java ends with a semicolon (;) (statement terminator).

[[id:5f2b572a-ec31-49de-ba13-95b0c5edb4c0][Keywords]] have a specific meaning to the [[id:44534722-acbc-4a80-8c65-3f76edefd7b5][compiler]] and cannot be used for other purposes in the program.

For example, when the [[id:44534722-acbc-4a80-8c65-3f76edefd7b5][compiler]] sees the word =class=, it understands that the word after =class= is the *name* for the class.

Every =class= has a class block that groups the ~data~ and ~methods~ of the =class=.

Blocks can be nested.

[[id:679d19b1-0db5-4057-ada0-1332230a6b8c][Java Special Characters]]
