:PROPERTIES:
:ID:       d78051a5-0858-4eb4-83d9-0de6da20ced7
:END:
#+title: Accessing Objects via Reference Variables

* Accessing Objects via Reference Variables

An =object’s= ~data~ and ~methods~ can be accessed through the =dot= (=.=) operator (aka *object member access operator*) via the =object’s= *reference* *variable*.

- Newly created objects are *allocated* in the *memory*.

** Syntax

~ClassName objectRefVar;~

A =class= is essentially a programmer-defined *type*.

- A class is a [[id:ef3f4798-9f1d-462f-8eea-df2b75e512f6][reference type]], which means that a *variable* of the =class= type can *reference* an *instance* of the =class=.

The following statement declares the variable ~myCircle~ to be of the =Circle= type:
#+BEGIN_SRC java
Circle myCircle;
#+END_SRC

- The variable ~myCircle~ can *reference* a =Circle= object.
- The next statement *creates* an *object* and assigns its *reference* to ~myCircle~:

#+BEGIN_SRC java
myCircle = new Circle();
#+END_SRC

You can write a single statement that combines the *declaration* of an =object= *reference* *variable*, the *creation* of an =object=, and the *assigning* of an =object= reference to the variable with the following syntax:

#+BEGIN_SRC java
ClassName objectRefVar = new ClassName();
#+END_SRC

*** Example

#+BEGIN_SRC java
Circle myCircle = new Circle();
#+END_SRC

- ~myCircle~ holds a *reference* to a =Circle= *object*.

** Reference Data Fields and the null Valuee

- The *data* *fields* can be of [[id:ef3f4798-9f1d-462f-8eea-df2b75e512f6][reference types]].

*** Example

- The following =Student= *class* contains a data field ~name~ of the =String= type.

#+BEGIN_SRC java
class Student {
    // name has the default value null
    String name;

    // age has the default value 0
    int age;

    // isScienceMajor has default value false
    boolean isScienceMajor;

    // gender has default value '\u0000'
    char gender;
}
#+END_SRC

- If a *data* *field* of a =reference= type does not reference any =object=, the data field holds a special Java value, ~null~.

- ~null~ is a *literal* just like ~true~ and ~false~.
  - While ~true~ and ~false~ are =Boolean= literals, ~null~ is a literal for a =reference= type.

- ~null~ is *not* a Java *keyword*, but it is a [[id:8799def5-f75d-4933-9b5e-aabd642107c4][Reserved Words]] in Java.

- The *default* *value* of a *data* *field* is ~null~ for a [[id:ef3f4798-9f1d-462f-8eea-df2b75e512f6][reference]], =0= for a [[id:4b7774f6-ef98-4e86-ae2c-49961d934c6f][numeric]], ~false~ for a [[id:d7a6412b-caff-4103-95ab-fb266ec855be][Boolean]], and ~\u0000~ for a [[id:8ec85e4d-ce23-471d-9afd-c9853ecae6fe][Character]].

However, Java assigns *no* =default= value to a *local* *variable* inside a method.

*** Example

The following code displays the =default= *values* of the data fields ~name~, ~age~, ~isScienceMajor~ and ~gender~ for a =Student= *object*:

#+BEGIN_SRC java
class Student {
    String name;
    int age;
    boolean isScienceMajor;
    char gender;
}

class TestStudent {
    public static void main(String[] args) {
        Student student = new Student();
        System.out.println("name? " + student.name); // name? null
        System.out.println("age? " + student.age); // age? 0
        System.out.println("isScienceMajor? " + student.isScienceMajor); // isScienceMajor? false
        System.out.println("gender? " + student.gender); // gender?
    }
}
#+END_SRC

*** Note

- The following has a *compile error*, because the *local* *variables* =x= and =y= are *not* *initialized*:

#+BEGIN_SRC java
class TestLocalVariables {
    public static void main(String[] args) {
        int x; // x has no default value
        String y; // y has no default value
        System.out.println("x is " + x); // DOES NOT COMPILE
        System.out.println("y is " + y); // DOES NOT COMPILE
    }
}
#+END_SRC

**** Note

- =NullPointerException= is a common *runtime* *error*.
  - It occurs when you invoke a ~method~ on a =reference= *variable* with a ~null~ value.

- Make sure you *assign* an =object= =reference= to the variable *before* invoking the =method= through the *reference variable*.
